
# FROM node:14.18.3 as builder
# FROM amd64/node:16-alpine as builder
FROM registry.cn-shenzhen.aliyuncs.com/mwcloud/node:20-alpine as builder


WORKDIR /source

COPY . .
# ADD package.json /source

# RUN rm -rf yarn.lock && rm -rf dist && rm -rf node_modules && yarn config set registry https://registry.npmmirror.com && yarn add antd@4.24.7 && yarn install && yarn build:prd

COPY . /source


# 选择更小体积的基础镜像
# FROM nginx:latest
# FROM amd64/nginx:latest
FROM registry.cn-shenzhen.aliyuncs.com/multiway/nginx:latest


COPY --from=builder /source/html/ /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf

# docker build -t localwms .