const a = {
  actions: [
    {
      action_id: "",
      action_type: "",
      intent: "",
      status: "",
      telemetry: {
        X轴: 0,
        Y轴: 0,
        Z轴: 80,
        pitch: 0,
        roll: 0,
        width: 0,
        "偏航角 (Yaw)": 0,
      },
      thought_process: [],
      timestamp: 0,
      title: "",
    },
    {
      action_id: "",
      action_type: "",
      intent: "",
      status: "",
      telemetry: {
        X轴: 0,
        Y轴: 0,
        Z轴: 80,
        pitch: 0,
        roll: 0,
        width: 0,
        "偏航角 (Yaw)": 0,
      },
      thought_process: [],
      timestamp: 0,
      title: "",
    },
  ],
  current_action_index: -1,
  event: "global_state_update",
  task: {
    pallet_name: "",
    task_id: 0,
    task_point_id: 0,
    task_state: 0,
    task_type: 0,
  },
  timestamp: 0,
};
