import { styled } from '@mui/material';

const ChargingContainer = styled('div')(() => ({
  position: 'fixed',
  left: 0,
  top: 0,
  height: '100vh',
  width: '100vw',
  zIndex: 1202,
  // background: 'linear-gradient(to bottom, #000000, #000000)',
  '.text': {
    width: '200px',
    height: '200px',
    textAlign: 'center',
    zIndex: 9,
    fontSize: '30px',
    lineHeight: '200px',
    color: 'white',
    position: 'absolute',
    left: '50%',
    top: '15%',
    transform: 'translate(-50%, 0%)',
  },
  '.contrast': {
    width: '100%',
    height: '100%',
    // backgroundColor: '#000',
    background: 'linear-gradient(to bottom, #00000060, #000000)',
    overflow: 'hidden',
    filter: 'contrast(5) hue-rotate(360deg)',
    position: 'relative',
    // animation: 'hueRotate 6s linear infinite'
  },
  '.contrast span': {
    background: '#00d1d1',
    position: 'absolute',
    bottom: '0',
    borderRadius: '100px 100px 0 0',
    filter: 'blur(5px)',
    animation: 'moveUp ease-in-out infinite',
    '&:nth-child(1)': {
      width: '20px',
      height: '20px',
      left: '50%',
      animationDuration: '4s',
      animationDelay: '2s',
    },
    '&:nth-child(2)': {
      width: '22px',
      height: '22px',
      left: '53%',
      animationDuration: '4.2s',
      animationDelay: '4s',
    },
    '&:nth-child(3)': {
      width: '24px',
      height: '24px',
      left: '45%',
      animationDuration: '3s',
      animationDelay: '1s',
    },
    '&:nth-child(4)': {
      width: '20px',
      height: '22px',
      left: '53%',
      animationDuration: '5s',
      animationDelay: '0s',
    },
    '&:nth-child(5)': {
      width: '22px',
      height: '22px',
      left: '52%',
      animationDuration: '3.5s',
      animationDelay: '5s',
    },
    '&:nth-child(6)': {
      width: '20px',
      height: '20px',
      left: '50%',
      animationDuration: '4.7s',
      animationDelay: '1.2s',
    },
    '&:nth-child(7)': {
      width: '22px',
      height: '22px',
      left: '53%',
      animationDuration: '2.5s',
      animationDelay: '3.5s',
    },
    '&:nth-child(8)': {
      width: '24px',
      height: '24px',
      left: '51%',
      animationDuration: '5.6s',
      animationDelay: '4.2s',
    },
    '&:nth-child(9)': {
      width: '26px',
      height: '26px',
      left: '46%',
      animationDuration: '5.2s',
      animationDelay: '4s',
    },
    '&:nth-child(10)': {
      width: '26px',
      height: '22px',
      left: '53%',
      animationDuration: '3.8s',
      animationDelay: '4.3s',
    },
    '&:nth-child(11)': {
      width: '22px',
      height: '22px',
      left: '46%',
      animationDuration: '4.2s',
      animationDelay: '0.3s',
    },
    '&:nth-child(12)': {
      width: '24px',
      height: '24px',
      left: '46%',
      animationDuration: '4.6s',
      animationDelay: '2s',
    },
    '&:nth-child(13)': {
      width: '22px',
      height: '22px',
      left: '48%',
      animationDuration: '3.8s',
      animationDelay: '3.2s',
    },
    '&:nth-child(14)': {
      width: '26px',
      height: '22px',
      left: '51%',
      animationDuration: '5.2s',
      animationDelay: '2.9s',
    },
    '&:nth-child(15)': {
      width: '26px',
      height: '22px',
      left: '52%',
      animationDuration: '4.9s',
      animationDelay: '4.2s',
    },
  },
  '.button': {
    width: '150px',
    height: '50px',
    background: '#00d1d1',
    position: 'absolute',
    left: '50%',
    bottom: '-2px',
    transform: 'translate(-50%, 0)',
    borderRadius: '100px 100px 0 0',
    filter: 'blur(5px)',
  },
  '.circle': {
    width: '300px',
    height: '300px',
    position: 'absolute',
    top: '10%',
    left: '50%',
    marginLeft: '-150px',
    boxSizing: 'border-box',
    filter: 'blur(6px)',
    animation: 'circleRotate 6s linear infinite',
    '&::before': {
      content: '""',
      height: '200px',
      width: '200px',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%) rotate(0)',
      background: '#00d1d1',
      borderRadius: '42% 38% 62% 49% / 45%',
    },
    '&::after': {
      content: '""',
      width: '176px',
      height: '178px',
      background: '#000',
      borderRadius: '50%',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
    },
  },
  '@keyframes moveUp': {
    '0%': {
      bottom: '0',
    },
    '100%': {
      bottom: 'calc(100% - 265px)',
    },
  },
  '@keyframes hueRotate': {
    '0%': {
      filter: 'contrast(15) hue-rotate(0)',
    },
    '100%': {
      filter: 'contrast(15) hue-rotate(360deg)',
    },
  },
  '@keyframes circleRotate': {
    '0%': {
      transform: 'rotate(0deg)',
    },
    '100%': {
      transform: 'rotate(360deg)',
    },
  },
}));

export default ChargingContainer;
